### ISSUE TITLE
problem with get_mut_type(data, type = "dbs", predefined_dbs_mbs = FALSE)

### ISSUE THREAD

**Issue by riccardobergamin** [ToolsVanBox/MutationalPatterns#2]
i am running the function get_mut_type(data, type = "dbs", predefined_dbs_mbs = FALSE) on a GenomicRanges object which has the form

<img width="1175" alt="Screenshot 2024-01-29 alle 16 14 40" src="https://github.com/ToolsVanBox/MutationalPatterns/assets/72212720/678834a7-3223-4d58-9ff4-2cb4ae6131ea">

But i am getting apparently wrong dbs context

<img width="410" alt="Screenshot 2024-01-29 alle 16 14 57" src="https://github.com/ToolsVanBox/MutationalPatterns/assets/72212720/173127b9-bb23-421a-ad44-95bd7cf9a242">

i am not understanding if it is a problem of the input object or a mistake of the function.
Thank you very much for the help.

**Comment by riccardobergamin** [comment]
@FreekManders

**Comment by FreekManders** [comment]
It seems you're getting both DBS and MBS in your results. That shouldn't happen. Does this also happen when you run the examples in the `get_mut_type` documentation?

**Comment by riccardobergamin** [comment]
Hi, 
yes, if i run it as in the example it works fine. But my gRanges object seems to be in the same form (the one that i attached), so i was wondering if there is some error there that i did't notice

**Comment by FreekManders** [comment]
Is it possible that your GRanges object already contains some predefined MBS or DBS? You could check this by setting predefined_dbs_mbs to TRUE.

**Comment by riccardobergamin** [comment]
i tried and it worked fine. probably that was problem, thank you!
